[build]
  publish = "build"
  command = "npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "24"
  NPM_VERSION = "10"
  NODE_OPTIONS = "--max-old-space-size=4096"
  CI = "false"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
